polls/polls/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
	path('polls/', include('vote4change.urls')),
	path('', 
		TemplateView.as_view(template_name='home.html'), name='about'),
    path('admin/', admin.site.urls),
]

polls/vote4change/urls.py
from django.urls import path
from . import views

app_name = "vote4change"



urlpatterns = [
	path('', views.index, name='index'),
	path('<int:pk>', views.detail, name='detail'),
	path('<int:pk>/result', views.result, name='result'),
	# vote handler
	path('<int:pk>/vote', views.vote, name='vote'),
	path('<str:object_id>/resultsdata/', views.result_data, name="result_data"),
]

polls/vote4change/models.py
# Create your models here.
from django.db import models


# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/vote4change/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from .models import Question, Choice

from django.http import JsonResponse
# Create your views here.


# first view: Get question and display them
def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {
		'latest_question_list': latest_question_list
	}
	return render(request, 'vote4change/index.html', context)

def detail(request, pk):
	question_obj = get_object_or_404(Question, id=pk)
	context = {
		'question': question_obj
	}
	return render(request, 'vote4change/detail.html', context)

def result(request, pk):
	question_obj = get_object_or_404(Question, id=pk)
	return render(request, 'vote4change/result.html', {'question': question_obj})

def vote(request, pk):
	question = get_object_or_404(Question, id=pk)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'vote4change/detail.html',
			{
			'question': question,
			'error_message': 'You did not select a choice'
			}
			)
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return redirect(reverse('vote4change:result', args=(question.id,)))


#  for chart
def result_data(request, object_id):
	votedata = []

	question = Question.objects.get(id=object_id)
	votes = question.choice_set.all()
	for i in votes:
		votedata.append({i.choice_text: i.votes})
	print(votedata)
	return JsonResponse(votedata, safe=False)

polls/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<title>Vote4Change {% block title %}{% endblock %}</title>
</head>
<body>
	<!-- navbar from partial-->
	{% include 'partials/_navbar.html' %}
	<div class="container">
		<div class="row">
			<div class="col-md-6 m-auto">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

polls/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="card text-center">
	<div class="card-body">
		<h1>Welcome To Vote4Change</h1>
		<p> A Django Poll app but prettier</p>
		<a class="btn btn-dark" href="{% url 'vote4change:index' %}">View Polls </a>
		
	</div>
	
</div>
{% endblock content %}

polls/templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
	<div class="container">
		<a class="navbar-brand" href="/polls">Vote4Change</a>
	</div>
</nav>

polls/templates/vote4change/detail.html
{% extends 'base.html' %}
{% block content %}
{% if error_message %}

	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'vote4change:index' %}">Back to Polls</a>
<div class="card mb-4">
	<div class="card-body">
		<p>{{question.question_text}}</p>
		<form action="{% url 'vote4change:vote' question.id %}" method="post">
			{% csrf_token %}
			{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
			<label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
			<br>
			{% endfor %}
			<input class="btn btn-success btn-lg btn-block mt-4" type="submit" name="" value="Vote">
			
		</form>
			
		
	</div>
	
</div>
{% endblock %}

polls/templates/vote4change/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center mb-3">Poll Questions</h1>
{% if latest_question_list %}
	{% for question in latest_question_list %}
		<div class="card mb-3">
			<div class="card-body">
				<p class="lead">{{ question.question_text }}</p>
				<a href="{% url 'vote4change:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
				<a href="{% url 'vote4change:result' question.id %}" class="btn btn-secondary btn-sm">Result</a>
				
			</div>
		</div>

	{% endfor %}
{% else %}
	<p>No polls available</p>
{% endif %}



{% endblock %}

polls/templates/vote4change/result.html
{% extends 'base.html' %}
{% block content %}
<!-- zing chart -->

<script src="https://cdn.zingchart.com/zingchart.min.js"></script>
<!-- Ajax -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



<h1 class="mb-5 text-center">
{{question.question_text}}
</h1>
<ul class="list-group">
{% for choice in question.choice_set.all %}
	<li class="list-group-item">
		<p>
			{{choice}} <span class="badge badge-success float-right">{{choice.votes}} vote{{ choice.votes|pluralize }}
			</span>

		</p>
	</li>
{% endfor %}
</ul>
<br>
<div id="myChart">
	
</div>

<div class="mb-5">
	<a class="btn btn-secondary mt-3" href="{% url 'vote4change:index' %}">Back to Poll</a>
	<a class="btn btn-secondary mt-3" href="{% url 'vote4change:detail' question.id %}">Vote Again?</a>
	
</div>

<script type="text/javascript">

	var state = {
		'items':[],
		'values':[],
	}

	var objectId = '{{question.id}}'
	var dataURL = `/polls/${objectId}/resultsdata/`
	$.ajax({
		method:'GET',
		url:dataURL,
		success:function(response){
			console.log('response:', response)
			for (var i in response){
				console.log("i:", response[i])
				console.log("works")
				var key = Object.keys(response[i])[0]
				console.log("THis")
				var value = Object.values(response[i])[0]
				state.items.push(key)
				state.values.push(value)

			}
			console.log("state", state)
			builChart()
		}
	})
	function builChart(){
			var chartData = {
			"type": "bar",
			"title": {
	    	"text": "View chart"
	  		},
			"scale-x": {
				"values":state.items
			},
			"series": [
				{
					"values":state.values
				}
			]


		}
		zingchart.render({
		id: "myChart",
		data: chartData,
		});

	}




	
</script>


{% endblock %}